version: '3.8'
services:
  gateway:
    image: gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "1244:1244"
    depends_on:
      - user-service
    networks:
      - my-network

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "5634:5634"
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
