spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:5634
          predicates:
            - Path=/api/users/**
server:
  port: 1244
