spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5634
